language: cpp
dist: xenial
env:
  global:
  - HUNTER_ROOT="${TRAVIS_BUILD_DIR}/hunter"
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/deps"
  - "$TRAVIS_BUILD_DIR/hunter"
branches:
stages:
- clang-format
- compile_dependencies # compile the hunter dependencies, i.e. configure the cmake project
- compile_test
jobs:
  include:
    - stage: clang-format
      os: linux
      addons:
        apt:
          update: true
          sources:
          - llvm-toolchain-xenial-8
          - ubuntu-toolchain-r-test
          packages:
          - clang-format-8
      script: "./scripts/ci/run-clang-format.py -r --clang-format-executable clang-format-8
        --color always ./developers/"
    - stage: compile_dependencies
      os: linux
      compiler: gcc
      env:
        - COMPILER='g++-7'
        - BUILD_TYPE='Debug'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script: "./scripts/ci/run_cmake.sh"
    - stage: compile_test
      os: linux
      compiler: gcc
      env:
        - COMPILER='g++-7'
        - BUILD_TYPE='Debug'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script: 
        - ./scripts/ci/run_cmake.sh
        - cd Build/developers
        - make -j${NUM_PROC:-2}
        - make test_developers_mastersolution
    - stage: compile_dependencies
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'
      script: "./scripts/ci/run_cmake.sh"
    - stage: compile_test
      os: osx
      osx_image: xcode10.2
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug'
      script: 
        - "./scripts/ci/run_cmake.sh"
        - cd Build/developers
        - make -j${NUM_PROC:-2}
        - make test_developers_mastersolution
  
